config/routes.rb
Rails.application.routes.draw do
  get 'searchs/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :comments,only: [:create,:destroy]
    resource :favorites,only: [:create,:destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :following,:followers
    end
  end
  resources :relationships, only: [:create,:destroy]
  get "searchs"=>"searchs#search",as: :search

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :body,presence: true

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment=Comment.new(comment_params)
    @comment.user_id=current_user.id
    @comment.book_id=params[:book_id]
    @comment.save
    # binding pry
    # redirect_to request.referer
    @book=Book.find(params[:book_id])
  end

  def destroy
    comment=Comment.find(params[:id])
    @book=Book.find(comment.book_id)
    comment.destroy
    # redirect_to request.referer
  end

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
        <div class="row">
          <div class="col-3">
            <span>
              <%= link_to user_path(comment.user) do %>
                <%= image_tag comment.user.get_profile_image, size: "60x60" %><br>
                <%= comment.user.name %>
              <% end %>
            </span>
          </div>
          <div class="col-4">
            <span>
              <%= comment.body %>
            </span>
          </div>
          <div class="col-2">
            <!--<span  class="btn btn-danger btn-sm">-->
            <% if comment.user==current_user %>
              <%= link_to "Destroy",book_comment_path(comment.book,comment),method: :delete,remote: true ,class: "btn btn-sm btn-danger delete-comment-target" %>
            <% end %>
              <!--</span>-->
          </div>
        </div>

app/views/comments/create.js.erb
$('.comment-index').append("<%= escape_javascript(render partial: 'comments/comment', locals: {comment: @comment})%>");
$('.comment-form')[0].reset();
$('.update-comment-create').html("コメント数：<%= @book.comments.count %>件");
$('.delete-comment-target').on('click',function(){
  $(this).parent().parent().addClass('row-delete-comment-target');
});

app/views/comments/destroy.js.erb
$('.row-delete-comment-target').remove();
$('.update-comment-create').html("コメント数：<%= @book.comments.count %>件");