config/routes.rb
Rails.application.routes.draw do
  get 'searchs/search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resources :comments,only: [:create,:destroy]
    resource :favorites,only: [:create,:destroy]
  end
  resources :users, only: [:index,:show,:edit,:update] do
    member do
      get :following,:followers
    end
  end
  resources :relationships, only: [:create,:destroy]
  get "searchs"=>"searchs#search",as: :search

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/controllers/searchs_controller.rb
class SearchsController < ApplicationController
  before_action :authenticate_user!

  def search
    # bindring pry
    @search=params
    if params[:model]=="Users"
      case params[:conditions]
      when "前方一致" then
        @objects=User.where('name like ?',"#{params[:query]}%")
      when "後方一致" then
        @objects=User.where('name like ?',"%#{params[:query]}")
      when "部分一致" then
        @objects=User.where('name like ?',"%#{params[:query]}%")
      when "完全一致" then
        @objects=User.where('name like ?',"#{params[:query]}")
      end
    else
      case params[:conditions]
      when "前方一致" then
        @objects=Book.where('title like ?',"#{params[:query]}%")
      when "後方一致" then
        @objects=Book.where('title like ?',"%#{params[:query]}")
      when "部分一致" then
        @objects=Book.where('title like ?',"%#{params[:query]}%")
      when "完全一致" then
        @objects=Book.where('title like ?',"#{params[:query]}")
      end
    end
    # bindring pry
  end
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/views/searchs/_search.html.erb
<div class="container">
  <div class="row mx-auto mb-5">
    <div class="col-md-8 offset-md-4">
      <%= form_with url: search_path,method: :get do |f| %>
        <%= f.text_field :query %>
        <%= f.select :model ,["Users","Books"] %>
        <%= f.select :conditions,["前方一致","後方一致","部分一致","完全一致"] %>
        <%= f.submit "検索" %>
      <% end %>
    </div>
  </div>
</div>

app/views/searchs/search.html.erb
<div class="container">
  <div class="row">
    <% if @search[:model]=="Users" %>
      <h2>User serach for "<%= @search[:query] %>"</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Name</th>
            <th>Introduction</th>
          </tr>
        </thead>
        <tbody>
          <% @objects.each do |user| %>
            <tr>
              <td><%= image_tag user.get_profile_image,size: '50x50' %> </td>
              <td>
                <%= link_to user_path(user) do %>
                  <%= user.name %>
                <% end %>
              </td>
              <td><%= user.introduction %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <h2>Book serach for "<%= @search[:query] %>"</h2>
      <table class='table table-hover table-inverse'>
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @objects.each do |book| %>
            <tr>
              <td><%= image_tag book.user.get_profile_image,size: '50x50' %> </td>
              <td>
                <%= link_to book_path(book) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td><%= book.body %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>